/* 
 * File:   mcal_interrupt_gen_cfg.h
 * Author: xcite
 *
 * Created on February 3, 2024, 1:21 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INTERRUPT_FEATURE_ENABLE   1      
#define INTERRUPT_FEATURE_DISABLE  1


//#define INTERRUPT_PRIORITY_LEVELS_ENABLE           INTERRUPT_FEATURE_ENABLE  
#define EXTERNAL_INTERRUPT_INTx_FEATURE_ENABLE     INTERRUPT_FEATURE_ENABLE
#define EXTERNAL_INTERRUPT_OnChange_FEATURE_ENABLE INTERRUPT_FEATURE_ENABLE

#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

